# services
# ".mounts" list all host mounts, path relative to configured data path (/usr/local/var/dev/<profile>/)
# This section only affect folder creation. The binding config is controlled by docker-compose.yml
services:
  -
    service: consul
    display_name: Consul
    display_version: 1.15.x
    image: consul:1.15
    mounts:
      - consul
  -
    service: vault
    display_name: Vault
    display_version: 1.12.6
    image: vault:1.12.6
    mounts:
      - vault/file
      - vault/root-home
  -
    service: redis
    display_name: Redis
    display_version: 6.2.x
    image: redis:6.2-alpine
  -
    service: zookeeper
    display_name: ZooKeeper
    display_version: 3.7.x
    image: zookeeper:3.7
    build_args:
      zookeeper_version: 3.4.14
  -
    service: kafka
    display_name: Kafka
    display_version: 2.8.2
    image: kafka:2.8.2-wurstmeister
    build_args:
      kafka_version: 2.8.2
      scala_version: 2.13
      glibc_version: 2.34-r0
  -
    service: opensearch
    display_name: Opensearch
    display_version: 2.6.0
    image: opensearchproject/opensearch:2.6.0
  -
    service: opensearch_ui
    display_name: Opensearch Dashboard
    display_version: 2.6.0
    image: opensearchproject/opensearch-dashboards:2.6.0
  -
    service: cockroachdb
    display_name: CockroachDB
    display_version: 22.2.x
    image: cockroachdb/cockroach:latest-v22.2
    mounts:
      - cockroachdb
  -
    service: jaeger
    display_name: JaegerTracing
    display_version: Latest 1.x
    image: jaegertracing/all-in-one:1


# pre_start should be shell scripts
#pre_start:
#  - pre-start-optest.sh
  
# pre_stop should be shell scripts  
#pre_stop:
#  - 
  
# post_start should be post start containers
post_start:
  - post_start_vault
  - post_start_consul



    
