# services
# ".mounts" list all host mounts, path relative to configured data path (/usr/local/var/dev/<profile>/)
# This section only affect folder creation. The binding config is controlled by docker-compose.yml
services:
  -
    service: consul
    display_name: Consul
    display_version: 1.15.x
    image: consul:1.15
    mounts:
      - consul
  -
    service: vault
    display_name: Vault
    display_version: 1.12.6
    image: vault:1.12.6
    mounts:
      - vault/file
      - vault/root-home
  -
    service: redis
    display_name: Redis
    display_version: 6.2.x
    image: redis:6.2-alpine
  -
    service: postgres
    display_name: PostgreSQL
    display_version: 16.x.x
    image: postgres:16-alpine
    mounts:
      - postgres
  -
    service: zookeeper
    display_name: ZooKeeper
    display_version: 3.7.x
    image: zookeeper:3.7
    build_args:
      zookeeper_version: 3.4.14
  -
    service: kafka
    display_name: Kafka
    display_version: 2.8.2
    image: kafka:2.8.2-wurstmeister
    build_args:
      kafka_version: 2.8.2
      scala_version: 2.13
      glibc_version: 2.34-r0
  -
    service: jaeger
    display_name: JaegerTracing
    display_version: Latest 1.x
    image: jaegertracing/all-in-one:1


# pre_start should be shell scripts, path relative to ${RESOURCE_DIR}/pre-start/
pre_start:
  - pre-start-example.sh

  
# post_start should be post start containers
post_start:
  - post-start-vault
  - post-start-consul

# pre_stop should be pre stop scripts, path relative to ${RESOURCE_DIR}/pre-stop/
pre_stop:
  - pre-stop-example.sh

# post_stop should be shell scripts, path relative to ${RESOURCE_DIR}/post-stop/
post_stop:
  - post-stop-example.sh